// 登录用户信息
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
// 侧边栏滑动
export const SIDEBAR_COLLAPSE = 'SIDEBAR_COLLAPSE';
// 修改密码弹窗
export const PASSWORD_MODAL_TOGGLE = 'PASSWORD_MODAL_TOGGLE';
// 更新川商大盘数据
export const UPDATE_CHUANSHANG_BOARD_MARKET = 'UPDATE_CHUANSHANG_BOARD_MARKET';
// 更新川商邮币卡数据
export const UPDATE_CHUANSHANG_POST_CARD = 'UPDATE_CHUANSHANG_POST_CARD';
// 更新吉商邮币卡数据
export const UPDATE_JISHANG_POST_CARD = 'UPDATE_JISHANG_POST_CARD';
// 更新深文所大盘数据
export const UPDATE_SHENWENSUO_BOARD_MARKET = 'UPDATE_SHENWENSUO_BOARD_MARKET';
// 更新深文所微盘数据
export const UPDATE_SHENWENSUO_MICRO_BOARD = 'UPDATE_SHENWENSUO_MICRO_BOARD';
// 更新粤国际微盘数据
export const UPDATE_YUEGUOJI_MICRO_BOARD = 'UPDATE_YUEGUOJI_MICRO_BOARD';
// 更新吉商微盘数据
export const UPDATE_JISHANG_MICRO_BOARD = 'UPDATE_JISHANG_MICRO_BOARD';
// 更新代理商本月总数据
export const UPDATE_AGENT_OVERVIEW_DATA = 'UPDATE_AGENT_OVERVIEW_DATA';
// 更新大盘佣金数据
export const UPDATE_BOARD_MARKET_BROKERAGE = 'UPDATE_BOARD_MARKET_BROKERAGE';
// 更新微盘佣金数据
export const UPDATE_MICRO_BOARD_BROKERAGE = 'UPDATE_MICRO_BOARD_BROKERAGE';
// 更新邮币卡佣金数据
export const UPDATE_POST_CARD_BROKERAGE = 'UPDATE_POST_CARD_BROKERAGE';
// 更新大盘某用户个人详情佣金数据
export const UPDATE_BOARD_MARKET_BROKERAGE_USER_DETAIL_DATA = 'UPDATE_BOARD_MARKET_BROKERAGE_USER_DETAIL_DATA';
// 更新微盘某用户个人详情佣金数据
export const UPDATE_MICRO_BOARD_BROKERAGE_USER_DETAIL_DATA = 'UPDATE_MICRO_BOARD_BROKERAGE_USER_DETAIL_DATA';
// 更新邮币卡某用户个人详情佣金数据
export const UPDATE_POST_CARD_BROKERAGE_USER_DETAIL_DATA = 'UPDATE_POST_CARD_BROKERAGE_USER_DETAIL_DATA';

//更新下载中心显示数据
export const UPDATE_DOWNLOAD_DATA = 'UPDATE_DOWNLOAD_DATA';



//////////////搜索数据
// 更新川商大盘搜索数据
export const UPDATE_CHUANSHANG_BOARD_MARKET_SEARCH = 'UPDATE_CHUANSHANG_BOARD_MARKET_SEARCH'; 

// 更新深文所大盘搜索数据
export const UPDATE_SHENWENSUO_BOARD_MARKET_SEARCH = 'UPDATE_SHENWENSUO_BOARD_MARKET_SEARCH';

// 更新深文所微盘搜索数据
export const UPDATE_SHENWENSUO_MICRO_BOARD_SEARCH = 'UPDATE_SHENWENSUO_MICRO_BOARD_SEARCH';

// 更新川商邮币卡搜索数据
export const UPDATE_CHUANSHANG_POST_CARD_SEARCH = 'UPDATE_CHUANSHANG_POST_CARD_SEARCH'; 

// 更新吉商邮币卡搜索数据
export const UPDATE_JISHANG_POST_CARD_SEARCH = 'UPDATE_JISHANG_POST_CARD_SEARCH';

// 更新吉商微盘搜索数据
export const UPDATE_JISHANG_MICRO_BOARD_SEARCH = 'UPDATE_JISHANG_MICRO_BOARD_SEARCH';

// 更新粤国际微盘搜索数据
export const UPDATE_YUEGUOJI_MICRO_BOARD_SEARCH = 'UPDATE_YUEGUOJI_MICRO_BOARD_SEARCH';

//更新居间商旗下用户列表数据
export const UPDATE_USERLIST_DATA = 'UPDATE_USERLIST_DATA';
//更新居间商旗下用户列表s搜索数据
export const UPDATE_USERLIST_DATA_SEARCH = 'UPDATE_USERLIST_DATA_SEARCH';

//更新红包用户列表数据
export const UPDATE_HONGBAOLIST_DATA = 'UPDATE_HONGBAOLIST_DATA';
//更新红包用户列表s搜索数据
export const UPDATE_HONGBAOLIST_DATA_SEARCH = 'UPDATE_HONGBAOLIST_DATA_SEARCH';

// 更新"信息资产分配的列表"
export const UPDATE_PEOPLE_LIST_WHO_HAVE_INFO_ASSET_DATA = 'UPDATE_PEOPLE_LIST_WHO_HAVE_INFO_ASSET_DATA';
// 更新"信息资产分配列表搜索数据"
export const UPDATE_PEOPLE_LIST_WHO_HAVE_INFO_ASSET_SEARCH = 'UPDATE_PEOPLE_LIST_WHO_HAVE_INFO_ASSET_SEARCH';

// 更新"已获得信息资产的列表"
export const UPDATE_GAIN_PEOPLE_LIST_WHO_HAVE_INFO_ASSET_DATA = 'UPDATE_GAIN_PEOPLE_LIST_WHO_HAVE_INFO_ASSET_DATA';
// 更新"已获得信息资产列表搜索数据"
export const UPDATE_GAIN_PEOPLE_LIST_WHO_HAVE_INFO_ASSET_SEARCH = 'UPDATE_GAIN_PEOPLE_LIST_WHO_HAVE_INFO_ASSET_SEARCH';

// 更新居间商旗下"已授权小金"列表
export const UPDATE_AUTHOR_USER_LIST_DATA = 'UPDATE_AUTHOR_USER_LIST_DATA';
// 更新居间商旗下"未授权小金"列表
export const UPDATE_NO_AUTHOR_USER_LIST_DATA = 'UPDATE_NO_AUTHOR_USER_LIST_DATA';

// 更新居间商旗下"已授权小金"列表搜索数据
export const UPDATE_AUTHOR_USER_LIST_SEARCH = 'UPDATE_AUTHOR_USER_LIST_SEARCH';

// 更新居间商旗下"未授权小金"列表搜索数据
export const UPDATE_NO_AUTHOR_USER_LIST_SEARCH = 'UPDATE_NO_AUTHOR_USER_LIST_SEARCH';


// 更新大盘佣金搜索数据
export const UPDATE_BOARD_MARKET_BROKERAGE_SEARCH = 'UPDATE_BOARD_MARKET_BROKERAGE_SEARCH';
// 更新微盘佣金搜索数据
export const UPDATE_MICRO_BOARD_BROKERAGE_SEARCH = 'UPDATE_MICRO_BOARD_BROKERAGE_SEARCH';
// 更新邮币卡佣金搜索数据
export const UPDATE_POST_CARD_BROKERAGE_SEARCH = 'UPDATE_POST_CARD_BROKERAGE_SEARCH';
// 更新大盘某用户个人详情佣金搜索数据
export const UPDATE_BOARD_MARKET_BROKERAGE_USER_DETAIL_SEARCH = 'UPDATE_BOARD_MARKET_BROKERAGE_USER_DETAIL_SEARCH';
// 更新微盘某用户个人详情佣金搜索数据
export const UPDATE_MICRO_BOARD_BROKERAGE_USER_DETAIL_SEARCH = 'UPDATE_MICRO_BOARD_BROKERAGE_USER_DETAIL_SEARCH';
// 更新邮币卡某用户个人详情佣金搜索数据
export const UPDATE_POST_CARD_BROKERAGE_USER_DETAIL_SEARCH = 'UPDATE_POST_CARD_BROKERAGE_USER_DETAIL_SEARCH';

// 更新下载中心搜索数据
export const UPDATE_DOWNLOAD_DATA_SEARCH = 'UPDATE_DOWNLOAD_DATA_SEARCH';

// 更新深文所入金送券显示数据
export const UPDATE_SHENWENSUO_VOUCHER_LIST_DATA = 'UPDATE_SHENWENSUO_VOUCHER_LIST_DATA';
// 更新深文所入金送券搜索数据
export const UPDATE__SHENWENSUO_VOUCHER_DATA_SEARCH = 'UPDATE__SHENWENSUO_VOUCHER_DATA_SEARCH';

//更新用户一度人脉数据
export const UPDATE_UNDER_USER_DATA = 'UPDATE_UNDER_USER_DATA';
//更新用户一度人脉搜索数据
export const UPDATE_UNDER_USER_SEARCH = 'UPDATE_UNDER_USER_SEARCH';

