// 登录用户信息
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
// 侧边栏滑动
export const SIDEBAR_COLLAPSE = 'SIDEBAR_COLLAPSE';
// 修改密码弹窗
export const PASSWORD_MODAL_TOGGLE = 'PASSWORD_MODAL_TOGGLE';
// 更新川商大盘数据
export const UPDATE_CHUANSHANG_BOARD_MARKET = 'UPDATE_CHUANSHANG_BOARD_MARKET';
// 更新川商邮币卡数据
export const UPDATE_CHUANSHANG_YBK = 'UPDATE_CHUANSHANG_YBK';
// 更新吉商邮币卡数据
export const UPDATE_JISHANG_YBK = 'UPDATE_JISHANG_YBK';
// 更新深文所大盘数据
export const UPDATE_SHENWENSUO_BOARD_MARKET = 'UPDATE_SHENWENSUO_BOARD_MARKET';
// 更新深文所微盘数据
export const UPDATE_SHENWENSUO_MICRO_BOARD = 'UPDATE_SHENWENSUO_MICRO_BOARD';
// 更新粤国际微盘数据
export const UPDATE_YUEGUOJI_MICRO_BOARD = 'UPDATE_YUEGUOJI_MICRO_BOARD';
// 更新代理商本月总数据
export const UPDATE_AGENT_OVERVIEW_DATA = 'UPDATE_AGENT_OVERVIEW_DATA';

//////////////搜索数据
// 更新川商大盘搜索数据
export const UPDATE_CHUANSHANG_BOARD_MARKET_SEARCH = 'UPDATE_CHUANSHANG_BOARD_MARKET_SEARCH'; 